### ISSUE TITLE
What are the maximum poster dimensions?

### ISSUE THREAD

**Issue by dhimmel** [DDD-Moore/dse#5]
I'm presenting a poster (see [archived poster list here](https://github.com/DDD-Moore/dse/blob/e1d2c7e00c550583bb8e2f9c95802045e60604e7/demo-poster-talk-list.csv), now missing from repo). What is the maximum height and width for the poster?

**Comment by strasser** [comment]
See the bottom of http://msdse.org/summit

**Comment by dhimmel** [comment]
From http://msdse.org/summit/:

> **Posters**: suggested size is 30” tall by 40” wide. There will be easels with foam backing boards for displaying posters in the hall.
